# Generated by Django 6.0.7 on 2026-09-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
