# Generated by Django 6.0.7 on 2026-08-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='ebook_file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
