# Generated by Django 6.0.7 on 2026-08-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_author_product_ebook_file_product_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
